"""
City editorial bodies for the top-25 indexable cities.

Generated 2026-05-09 as part of the F4(b) editorial sprint. Each editorial is
a markdown string rendered to HTML at build time via the existing markdown
filter in build.py. Variant assignment per city is hash(slug) % 5:

  variant 0 (geography-led):       7 cities
  variant 1 (services-led):        6 cities
  variant 2 (state-licensing-led): 4 cities
  variant 3 (Care-Compare-led):    2 cities
  variant 4 (planning-led):        6 cities

Structural-variation checks (preview gate):
  Check A — first-30-char duplicate rate: max 1/25 = 4.0% (threshold 5%)  PASS
  Check B — 5-random-100-char-window collision: 0 actual duplicates (125
    distinct windows from 125 samples)                                    PASS

The keys here are city slugs as stored in the agency data (slugify of city
name). build_city_pages() looks up CITY_EDITORIALS.get(city_slug) and passes
the markdown to the template. Cities outside this set get no editorial.
"""

CITY_EDITORIALS = {
    "las-vegas": """Across the 95 home-care agencies serving Las Vegas listed in our directory, the most common services on offer are personal care (bathing, dressing, daily hygiene), companion care (presence, conversation, transportation to appointments), and overnight or live-in coverage. A large minority also list dementia and Alzheimer's care, hospice support, and post-surgery recovery care — services particularly common in a metro with a high concentration of retirement communities and a senior population that often ages in place rather than relocating.

Pricing in Las Vegas tracks the regional average for the Mountain West. Hourly rates for non-medical companion care are typically lower than coastal-California or Northeast metros; live-in arrangements are the dominant cost-saving option for families with full-day needs. Several of the 95 agencies advertise bilingual English-Spanish caregivers, reflecting the metro's diverse senior population. A subset focuses on care for veterans — Nevada has a substantial veteran population through Nellis Air Force Base, the VA Southern Nevada Healthcare System, and the broader Western military retiree community.

Nevada regulates home-care agencies through the Division of Public and Behavioral Health, Bureau of Health Care Quality and Compliance ([dpbh.nv.gov](https://dpbh.nv.gov/)). Verify any agency's license there before signing a service agreement. Nevada's Medicaid Home and Community-Based Services waiver — the Frail Elderly waiver — is a meaningful payment path for qualifying seniors who would otherwise need nursing-facility-level care; agencies on this page that accept Medicaid are usually flagged in their service detail.

For Medicare-certified agencies — a smaller subset, typically those offering skilled nursing alongside personal care — Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes overall quality star ratings, patient-experience survey scores (HHCAHPS), and any recent surveyor findings. Use Care Compare for the certified subset; use state licensing for the broader pool of non-Medicare companion-care and personal-care agencies. Both tools are free; both are worth the family's time before engagement.

A geographic note: many Las Vegas-listed agencies serve clients across the broader Clark County area, including Henderson, North Las Vegas, Boulder City, and the Summerlin and Spring Valley areas. Some reach into Pahrump or even Mesquite. Confirm the actual service area in writing if your loved one is outside the city core, and ask about caregiver-travel surcharges if applicable.

If you're new to comparing agencies, the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) walks through the four steps that matter most: license verification, real client references, caregiver vetting, and Care Compare for the certified subset. We provide this directory as informational; we do not endorse specific agencies, and the responsibility for verification rests with the family.""",

    "indianapolis": """Choosing home care in Indianapolis usually starts with a few practical questions families work out together: how many hours per week is the realistic need; whether overnight or weekend coverage is required; how the family expects to pay (private pay, long-term care insurance, the state Medicaid waiver, VA benefits if the loved one is a veteran); and whether the caregiver match matters more than the agency's brand. The 87 agencies in our Indianapolis listings differ across each of those dimensions. Some specialize in short shifts and companion care; some specialize in 24-hour coverage and skilled nursing; a smaller subset is Medicare-certified and bills directly for home health services. The brand-name national franchises (Comfort Keepers, Home Instead, Visiting Angels, BrightStar, Right at Home) are well-represented; so are independently-owned local operators that families often prefer for caregiver consistency.

Two preparation steps before the first phone call save time on every call after: write down the loved one's actual care needs in plain English (bathing twice a week, meals, two pharmacy runs a week, overnight presence on Mondays and Thursdays) and decide which payment sources you'll be combining. That clarity changes the conversation with the agency from "tell me what you offer" to "here's what we need; can you do it." It also exposes mismatches early — if an agency cannot do overnight coverage on weekdays, knowing that on the first call saves a wasted intake visit.

Indiana regulates home-care services through the Department of Health ([in.gov/health](https://www.in.gov/health/)). The state's Aged and Disabled Medicaid waiver is a meaningful payment path for eligible seniors who would otherwise require nursing-facility-level care; the waiver covers attendant services, homemaker services, respite, and adult day services in many regions. For families with VA-eligible veterans, the VA Aid and Attendance pension benefit is another commonly-used payment source — particularly with Indianapolis's substantial military-retiree population through Crane and Camp Atterbury and the broader Indianapolis VA Medical Center catchment.

For Medicare-certified agencies, the federal [Care Compare](https://www.medicare.gov/care-compare/) tool publishes overall quality star ratings, patient-experience survey results, and any recent surveyor findings. Read sample size carefully — Care Compare publishes the response count alongside the star ratings, and a four-star rating with eight responses is a different signal than a four-star rating with eighty.

A service-area note: many Indianapolis-listed agencies cover the broader Marion County area and reach into Hamilton, Hancock, Hendricks, Johnson, Boone, and Madison counties. Some serve only the Indianapolis core. Confirm in writing the agency's specific coverage for your loved one's home address.

The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers license verification, reference calls, caregiver vetting, and Care Compare interpretation. This directory lists agencies for research; it does not rank them or recommend any one over another, and verification before engagement is the family's responsibility.""",

    "omaha": """For Medicare-certified home health agencies operating in Omaha — a meaningful subset of the 85 listings on this page — Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool is the closest thing the public has to an objective quality benchmark. Care Compare publishes the agency's overall quality star rating, patient-experience survey results (HHCAHPS, the standardized survey CMS administers), and any recent surveyor findings. It only covers Medicare-certified service lines, so private-pay companion care and personal care without a Medicare component won't appear — but for the certified subset, it is the most authoritative data the federal government makes public. The companion guide ([how to use Medicare Care Compare](/guides/how-to-use-medicare-care-compare.html)) walks through the lookup tool, what to read in the star ratings, and where the limits of the data are.

A practical interpretive note specific to mid-sized metros like Omaha: agency-by-agency star-rating spread tends to be wider than in coastal mega-metros where individual agencies have been Medicare-certified for decades and have settled into similar performance bands. Some Omaha-area Medicare-certified agencies are local nonprofits with deep community ties; some are regional or national for-profit chains; some are hospital-affiliated discharge networks (Nebraska Medicine, CHI Health, Methodist Health System). The ownership type, listed on each Care Compare profile, is a useful frame for interpreting the rating context.

For non-Medicare-certified agencies — the larger pool of Omaha-area listings on this page — Nebraska regulates home-care services through the Department of Health and Human Services Health Facility Licensure ([dhhs.ne.gov](https://dhhs.ne.gov/)). The state's Aged and Disabled Medicaid waiver supports in-home personal care and homemaking services for qualifying seniors who meet income and care-need thresholds. Eastern Nebraska Office on Aging serves the Omaha metro and operates as the regional Area Agency on Aging — they maintain provider directories and can answer process questions during a care transition.

For families coordinating care across the Omaha-Council Bluffs metro, note that Iowa licenses home-care services separately from Nebraska. An agency providing services to a loved one whose home is in Iowa (Council Bluffs, Carter Lake) needs an Iowa license; an agency serving a Nebraska address needs a Nebraska license. Headquarters location alone is not sufficient. Confirm in writing.

The [verification guide](/guides/how-to-verify-a-home-care-agency.html) covers license verification, reference calls, caregiver-vetting questions, and Care Compare interpretation in detail. We don't independently rate any agency; this directory is informational and for family-side research, not endorsement.""",

    "harrisburg": """Pennsylvania has one of the more developed regulatory frameworks for home-care licensing in the country, established when state legislation separated home-care agency licensure from home health agency licensure as distinct license categories. Two license types exist: home care agencies (covering non-medical personal and companion care) and home health agencies (covering Medicare-certified skilled nursing and therapy services). The Pennsylvania Department of Health, through its Home Care Agency Licensing program, oversees both ([health.pa.gov](https://www.health.pa.gov/)). Before engaging any of the 73 agencies serving Harrisburg in this directory, verify the agency's license type matches the services you're contracting for — a home care agency cannot bill Medicare for skilled nursing; a home health agency may decline to take a private-pay companion-care case unless they offer that service line separately.

The licensure distinction has practical implications for families. If a parent is being discharged from a Pennsylvania hospital and Medicare will pay for short-term skilled nursing or physical therapy, that work goes to a home health agency. If the same parent then needs ongoing personal-care assistance after the Medicare benefit period ends, the family typically transitions to a home-care agency for non-medical services. Some agencies hold both licenses and can manage the transition under one roof; many specialize in one or the other. Ask in the first call.

For Medicare-certified agencies in the Harrisburg metro, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) provides quality star ratings, patient-experience survey results, and any recent surveyor findings. Pennsylvania's Community HealthChoices managed-care program, administered through HealthChoices managed-care organizations, is the state's Medicaid program for older adults and adults with physical disabilities — it consolidated several earlier Medicaid waivers and now covers most home and community-based care in the state for eligible beneficiaries.

Beyond licensure: Pennsylvania's Area Agencies on Aging (in the Harrisburg metro, that's the Tri-County Office of Aging serving Cumberland, Dauphin, and Perry counties, or the Cumberland County Aging and Community Services office for residents specifically in Cumberland County) vet and refer to home-care providers and can be a useful second opinion for families coordinating care across multiple services. AAAs are funded under the federal Older Americans Act and have a defined oversight role — their referral list is not a marketing list.

The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers license verification, reference calls, caregiver vetting, and Care Compare interpretation. The directory below is informational; we do not verify agencies on an ongoing basis ourselves, and the four-step verification framework rests with the family.""",

    "st-louis": """Of the 68 home-care agencies serving St. Louis listed in our directory, the Medicare-certified subset — typically those offering skilled nursing or therapy alongside personal-care services — appears in Medicare's [Care Compare](https://www.medicare.gov/care-compare/) database with overall quality ratings, patient-experience survey results (HHCAHPS), and any recent state-survey findings. Care Compare is one of the few apples-to-apples quality signals available to families comparing agencies. Read it carefully: a four-star agency with a single-digit number of patient-survey responses is statistically different from a four-star agency with a hundred responses, even though both display the same star count. Our [companion guide](/guides/how-to-use-medicare-care-compare.html) explains what's behind the stars and how to weigh patient-experience scores against quality-of-care scores.

A few St. Louis-specific Care Compare interpretive notes. The metro's Medicare-certified agencies fall along a wide ownership spectrum — from BJC HomeCare and SSM Health at Home (large hospital-affiliated networks) to regional independent operators. Hospital-affiliated agencies often have higher post-discharge care continuity scores; smaller operators sometimes show stronger patient-experience ratings on the questions about caregiver consistency and communication. Neither pattern is universal; both are worth a look on the Care Compare side-by-side compare view.

For non-Medicare-certified agencies — typically private-pay companion care and personal care — Missouri licenses through the Department of Health and Senior Services, Section for Long Term Care Regulation ([health.mo.gov](https://health.mo.gov/)). Missouri's HealthNet (Missouri Medicaid) covers in-home personal care under several program structures, including the In-Home Services program for adults with disabilities. The Mid-East Area Agency on Aging serving St. Louis County and the City of St. Louis maintains provider directories and provides care-coordination services that can be a useful second opinion for families managing multiple care decisions simultaneously.

For families coordinating care across the bi-state metro (Missouri-Illinois), note that Illinois licenses home-care services separately from Missouri. An agency providing care in an Illinois home (East St. Louis, Belleville, Edwardsville, Alton) needs Illinois licensure through the Illinois Department of Public Health; the same agency serving a Missouri home needs Missouri licensure. Many St. Louis-listed agencies hold both. Verify before engagement.

The [verification guide](/guides/how-to-verify-a-home-care-agency.html) covers what to do beyond Care Compare: state license verification, real client references, caregiver background and training questions. This directory is informational. The four-step framework — license, references, caregiver vetting, Care Compare for the certified subset — applies to every agency on the list.""",

    "brooklyn": """Across the 67 home-care agencies serving Brooklyn in this directory, the service mix tends to skew toward what a dense, multilingual urban borough actually needs: personal care, companion care, post-surgery recovery, dementia and Alzheimer's care, and live-in coverage. A meaningful subset offers specialized services for adults with developmental disabilities aging into older adulthood, mental-health-affiliated care coordination, and post-acute hospital-discharge support. Many Brooklyn agencies advertise multilingual caregivers — Russian, Spanish, Mandarin, Cantonese, Yiddish, Polish, and Haitian Creole are all common. For families coordinating care for a loved one whose first language isn't English, language match is often the single most important factor in caregiver satisfaction.

New York's home-care licensing structure is one of the more developed in the country. Both Licensed Home Care Services Agencies (LHCSAs, the dominant license type for non-Medicare home care in NYC) and Certified Home Health Agencies (CHHAs, the Medicare-certified type) operate in Brooklyn, and the New York State Department of Health's [Bureau of Home Care and Hospice](https://www.health.ny.gov/) oversees both. The license types matter for payment: LHCSAs typically work with Medicaid Managed Long Term Care (MLTC) plans, private pay, and long-term care insurance; CHHAs handle Medicare-certified skilled care. Some agencies hold both.

New York's Medicaid program is the dominant payer for in-home care for eligible Brooklyn seniors, primarily through MLTC plans (Fidelis, VillageCareMAX, Healthfirst Senior Health Partners, Centers Plan, ArchCare, GuildNet, MJHS Elderplan, and several others). Each MLTC plan contracts with a network of LHCSAs; an agency on this page that takes Medicaid is almost always operating through one or more MLTC plan contracts. If your loved one is enrolled in MLTC, the plan's care manager will direct which agencies are in-network; if your loved one is not yet enrolled, the local Department of Social Services or a Medicaid enrollment broker can explain eligibility.

Medicare-certified agencies are surveyed by the federal government and appear in Medicare's [Care Compare](https://www.medicare.gov/care-compare/) database with quality star ratings and patient-experience scores.

A geographic note: many Brooklyn-listed agencies serve clients across multiple boroughs — particularly Queens and Manhattan, where caregivers often travel from a Brooklyn-headquartered agency. Confirm in writing the agency's coverage and the rates for caregivers traveling to a non-Brooklyn home address. Use the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) before engaging. We list these agencies for research purposes; we don't rank them or endorse any one of them.""",

    "pittsburgh": """Hiring home care in Pittsburgh tends to involve a few overlapping decisions families don't always realize they're making at the same time: the type of care (companion-only, personal care, skilled nursing, or some combination), the schedule (a few hours a few times a week, full days, overnights, or live-in), the funding source (private pay, long-term care insurance, Medicare for short-term skilled care, Pennsylvania's Community HealthChoices Medicaid managed-care program for eligible seniors, or VA benefits), and the agency's geographic coverage (some Pittsburgh-listed agencies serve the city core only; others reach into Allegheny, Westmoreland, Washington, and Butler counties).

Of the 65 agencies on this page, some specialize narrowly (a hospice-support specialist, a dementia-only agency, a post-hospital-discharge home-health provider) and others offer the full range of in-home services. The agencies affiliated with the major Pittsburgh hospital systems (UPMC HomeCare, Allegheny Health Network home services, Excela Health Home Care) handle hospital-discharge transitions; the franchise-brand agencies (Comfort Keepers, Home Instead, Visiting Angels, BrightStar, Right at Home) emphasize private-pay personal and companion care; independently-owned local agencies often emphasize caregiver consistency and family communication.

Pennsylvania's licensure structure separates home-care agencies from home-health agencies (see our [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) for the distinction). The Pennsylvania Department of Health, Home Care Agency Licensing ([health.pa.gov](https://www.health.pa.gov/)) is the state regulator for both. Confirm in writing that the agency's license type matches the services contracted — a home-care agency cannot bill Medicare for skilled nursing; a home-health agency may decline private-pay companion-care work.

For Medicare-certified agencies, the [Care Compare](https://www.medicare.gov/care-compare/) database publishes quality star ratings and patient-experience survey results.

Pittsburgh's Area Agency on Aging — administered by Allegheny County Department of Human Services Area Agency on Aging — also vets and refers to home-care providers in Allegheny County and offers care management services for eligible seniors. They are funded under the federal Older Americans Act and have a defined oversight role; their referral list is not a marketing list.

We list agencies. We don't rate them. Verification before engagement is the family's job; the framework — license, references, caregiver vetting, Care Compare for the certified subset — is in the guide linked above. This directory is informational.""",

    "new-york": """Manhattan is one of the densest senior-care markets in the country, and the 65 agencies on this page are concentrated in the Upper East Side, Upper West Side, Midtown, the Financial District, and Washington Heights. The metro context matters: many of these agencies also serve clients in Brooklyn, Queens, the Bronx, Staten Island, and Westchester. A Manhattan address on the agency's listing page does not always mean Manhattan-only service. Ask before assuming. For families considering an out-borough loved one served by a Manhattan-headquartered agency, confirm in writing the actual service area and the rates for caregivers traveling outside the home borough.

New York is also one of the more heavily-regulated home-care states. The [New York State Department of Health, Bureau of Home Care and Hospice](https://www.health.ny.gov/) oversees both Licensed Home Care Services Agencies (LHCSAs, the dominant license type for non-Medicare home care in NYC) and Certified Home Health Agencies (CHHAs, the Medicare-certified type). The licensure types map to different payment sources: LHCSAs typically work with private pay, long-term care insurance, and Medicaid Managed Long Term Care plans; CHHAs handle Medicare-certified skilled care under federal certification.

For families using New York's Medicaid Managed Long Term Care benefits, the agency's MLTC-network status is its own line of inquiry. Each MLTC plan (Fidelis, Healthfirst Senior Health Partners, VillageCareMAX, ArchCare, GuildNet, MJHS Elderplan, Centers Plan, and others) maintains its own contracted-agency network. If your loved one is enrolled in MLTC, the plan's care manager directs which LHCSAs are accessible; if not yet enrolled, the local Department of Social Services or a Medicaid enrollment broker (NYIA, the New York Independent Assessor) can explain eligibility and the assessment process.

Manhattan also has a substantial concentration of nonprofit and hospital-affiliated home-care providers — the Visiting Nurse Service of New York, RiverSpring at Home (associated with the Hebrew Home), MJHS, ArchCare (Catholic-system), and several others. These often have deeper care-coordination capabilities for medically-complex cases than smaller for-profit operators.

Medicare-certified agencies — the smaller subset offering skilled nursing — appear in Medicare's [Care Compare](https://www.medicare.gov/care-compare/) database with quality star ratings and patient-experience scores. The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) is the first read before any engagement decision. This directory is informational; we don't recommend specific agencies, and verification before engagement is the family's responsibility.""",

    "cincinnati": """Ohio licenses home health agencies through the Department of Health, with separate paths for non-Medicare home-care services and Medicare-certified home-health services. The Ohio Department of Health ([odh.ohio.gov](https://odh.ohio.gov/)) is the state regulator; license lookup, complaint filing, and survey results for licensed agencies are accessible through the department. Before engaging any of the 58 agencies serving Cincinnati on this page, verify the agency's license is current and matches the type of service the family is contracting for. The license-lookup tool also flags any recent enforcement actions or surveyor findings — useful context that doesn't appear on the agency's own marketing.

Ohio's PASSPORT Medicaid waiver is one of the longest-running home and community-based services programs in the country and remains the principal Medicaid pathway for in-home care for eligible seniors in the Cincinnati metro. The Council on Aging of Southwestern Ohio administers PASSPORT for the Cincinnati region (Hamilton, Butler, Clermont, Clinton, and Warren counties) and serves as the regional Area Agency on Aging — they vet and refer to home-care providers, conduct in-home assessments, and offer ongoing care coordination for enrolled seniors. They are funded under the federal Older Americans Act with a defined oversight role; the referral list is not a marketing list.

Cincinnati's senior-care market overlaps with Northern Kentucky, and several agencies in the directory serve clients in both Hamilton County and Kenton, Boone, or Campbell counties across the Ohio River. Kentucky and Ohio license home care separately, so an agency operating across the metro should hold both states' licenses for the geography it covers — verify the relevant state's license for the actual home address, not just the agency's headquarters location. The same agency operating in Indiana (the Lawrenceburg corridor) needs Indiana licensure as well.

For Medicare-certified agencies in the Cincinnati metro, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes overall quality-of-care ratings, patient-experience survey results (HHCAHPS), and any recent CMS or state-survey findings. The federal data set covers Medicare-certified service lines specifically; non-Medicare home care is regulated and visible through the state's licensing authority.

The [verification guide](/guides/how-to-verify-a-home-care-agency.html) covers the rest of what we'd advise checking before engagement: real client references, caregiver background-check and training questions, and Care Compare interpretation. We provide listings; we don't verify agencies on an ongoing basis ourselves or recommend any one in particular.""",

    "fort-wayne": """Three scenarios drive the bulk of home-care decisions in Fort Wayne: keeping a parent at home a little longer rather than transitioning to assisted living; supporting recovery after a hospital discharge; and relieving a family caregiver who has been carrying too much for too long. The 56 agencies on this page collectively cover each of those scenarios, but they are not interchangeable. Some are specialist hospice-support providers; some offer overnight and live-in coverage; some are Medicare-certified home-health agencies handling short-term post-discharge care; some are non-medical companion-care agencies that don't take Medicare or Medicaid at all. Identifying which subset fits the actual care need is the most efficient first step.

Working out a few practicalities before the first phone call helps. Write down the loved one's specific needs (which hours of the day, which days of the week, what tasks). Identify the funding source you expect to use (private pay, long-term care insurance, Medicare for short-term skilled care, Indiana's Aged and Disabled Medicaid waiver, or VA Aid and Attendance for veterans). Decide who in the family is the lead point of contact for the agency. That clarity changes the conversation from "tell me what you offer" to "here is what we need; can you do it."

Indiana regulates home-care services through the Department of Health ([in.gov/health](https://www.in.gov/health/)). The state's Aged and Disabled Medicaid waiver is a meaningful payment path for eligible families and is worth understanding before settling on payment. The Aging and In-Home Services of Northeast Indiana — the regional Area Agency on Aging serving Allen and surrounding counties — administers the waiver assessment, maintains a provider directory, and offers care-management services for enrolled seniors. AAAs are funded under the federal Older Americans Act and have a defined role in oversight; their referral list is not a marketing list.

For the Medicare-certified agencies on the page, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) publishes overall quality star ratings and patient-experience survey results. Read sample sizes alongside ratings — a four-star agency with a small response count is a different signal than the same rating with a hundred respondents.

Northeast Indiana also has a meaningful veteran population through Camp Atterbury and the broader Indiana National Guard footprint; VA Aid and Attendance pension benefits cover in-home care for qualifying veterans and their surviving spouses. Several agencies on this page specialize in VA-billed care and can help families navigate the application.

Our [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers license lookup, reference calls, caregiver vetting, and Care Compare interpretation. This directory is informational and is not a recommendation of any specific agency.""",

    "rochester": """The 55 home-care agencies serving Rochester in this directory cover the typical service mix for a mid-sized Northeastern metro — personal care, companion care, dementia and Alzheimer's care, hospice support, post-surgery recovery, and live-in coverage are all widely available. A subset specializes in particular niches: post-stroke rehabilitation, complex-care or ventilator-dependent home support, end-of-life palliative coordination, and care for adults with developmental disabilities transitioning into older adulthood. The breadth of specialty options is one of the practical advantages of being in a regional medical hub like Rochester — the depth of clinical expertise locally translates into a depth of home-care specialty options.

Rochester's home-care market is shaped in part by the region's strong nonprofit and hospital-affiliated networks. The Visiting Nurse Service of Rochester, Rochester Regional Health home services, UR Medicine Home Care, and Lifespan all operate as Medicare-certified home health agencies with substantial scale. Several smaller nonprofits and faith-affiliated agencies (Catholic Family Center, Episcopal SeniorLife, Jewish Senior Life, Lifetime Care) provide both Medicare-certified and private-pay services. Franchise-brand agencies (Comfort Keepers, Home Instead, Visiting Angels, BrightStar, Right at Home) are well-represented as well, particularly for private-pay companion care; independently-owned local operators tend to emphasize caregiver consistency.

New York's home-care licensure structure separates Licensed Home Care Services Agencies (LHCSAs, the dominant license type for non-Medicare home care) from Certified Home Health Agencies (CHHAs, the Medicare-certified type). The state regulator is the [New York State Department of Health, Bureau of Home Care and Hospice](https://www.health.ny.gov/). The license type matters for payment: LHCSAs work with private pay, long-term care insurance, and Medicaid Managed Long Term Care plans; CHHAs handle Medicare-certified skilled care.

For families using New York's Medicaid Managed Long Term Care benefits, the agency's MLTC-network status is its own line of inquiry. Lifespan operates a Lifespan Aging Resources Center in the Rochester region and provides care-coordination services and provider directories for seniors and their families. The Monroe County Office for the Aging is the local Area Agency on Aging.

Medicare-certified agencies are surveyed by the federal government; their data is on Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool with quality star ratings, patient-experience survey results, and any recent surveyor findings. The directory is informational. Verify before engaging — that responsibility rests with the family.""",

    "miami": """Miami's 53 home-care agencies offer the service breadth typical of a major metro with a large, multi-generational, multilingual senior population. Personal care and companion care dominate the listings; dementia and Alzheimer's care, hospice support, post-surgery recovery, and live-in or 24-hour arrangements are all common. Many Miami-area agencies advertise bilingual caregivers — Spanish predominantly, Haitian Creole significantly, Portuguese, French, and Russian as well. For Spanish-dominant or Creole-dominant clients, language match is often the single most important factor in caregiver satisfaction. Several agencies focus specifically on care for the Cuban-American senior population that established South Florida's earliest large Spanish-speaking communities; others specialize in Caribbean and Haitian-American clients with deep cultural-care competency.

Florida regulates home-care services through the Agency for Health Care Administration ([ahca.myflorida.com](https://ahca.myflorida.com/)), which licenses several distinct categories: home health agencies, nurse registries, and home-care services agencies. The license type matters: a home health agency can deliver Medicare-certified skilled care; a nurse registry is a referral service that places independent caregivers (with a different liability profile for the family — the nurse-registry caregiver is typically not an employee of the agency and worker's-compensation and tax obligations may sit with the family); a home-care services agency provides non-medical companion and personal care under contract with the family. Confirm in writing which license category your prospective agency holds and how it matches the family's needs.

AHCA operates a license-lookup tool and complaint registry. The agency also surveys Medicare-certified providers and publishes inspection results. The Statewide Medicaid Managed Care Long-Term Care (SMMC LTC) program is a major payer for eligible Miami-Dade seniors; the program is administered through Medicaid managed-care organizations (Sunshine Health, Humana Long-Term Care, Simply Healthcare, UnitedHealthcare, Molina, and others), each with its own network of contracted home-care providers. If your loved one is enrolled in SMMC LTC, the plan's care manager directs which agencies are accessible.

For Florida's substantial veteran population, VA Aid and Attendance pension benefits cover in-home care for qualifying veterans and their surviving spouses. Several Miami-listed agencies specialize in VA-billed care.

Medicare's [Care Compare](https://www.medicare.gov/care-compare/) covers the federally-certified subset with quality star ratings and patient-experience survey results. For families weighing which agency to engage, the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers license verification, reference calls, caregiver-vetting questions, and Care Compare interpretation. We list agencies; we don't endorse any one. The verification work is the family's; the framework is the family's.""",

    "phoenix": """Phoenix's senior-care market reflects a region with a large retiree population and several distinct seasonal patterns — summer heat that makes daily check-ins critical for safety, a year-round senior population that has aged in place from the city's mid-twentieth-century retirement-community boom, and a winter influx of part-time residents who need short-stay coverage. The 52 agencies on this page collectively serve all three patterns, though not every agency covers all three. Some specialize in long-term ongoing personal care; some in short-term post-discharge home-health; some in companion care for snowbird seniors who arrive each fall and depart each spring. Identifying which subset matches the actual care need is the most efficient first step before any agency call.

Before deciding among them, write down the actual care need in plain language: specific tasks (bathing, medication reminders, meal prep, errands, overnight presence), hours per week, days of the week, payment source. Then look at which subset of the agencies on this page actually does that work. Some agencies will not take cases under a minimum hour threshold; some require minimum-shift commitments; some specialize in 24-hour care and do not offer hourly. Knowing the actual need before calling sharply reduces the time spent on bad-fit conversations.

Arizona regulates home-care services through the Department of Health Services, Bureau of Medical Facilities Licensing ([azdhs.gov](https://www.azdhs.gov/)). The Arizona Long Term Care System (ALTCS) is the state's Medicaid program for qualifying seniors and adults with disabilities; eligible seniors enrolled in ALTCS receive in-home care through one of the program's contracted health plans. The Maricopa County Region IV-A Area Agency on Aging serves the Phoenix metro and provides assessment, care coordination, and provider directories.

For Phoenix's substantial veteran population — the Phoenix VA Health Care System is one of the largest VA medical centers in the country — VA Aid and Attendance benefits and the Veteran Directed Care program are commonly-used payment paths for in-home care.

For Medicare-certified agencies, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes overall quality star ratings, patient-experience survey results, and any recent CMS or state-survey findings. Banner Home Care, HonorHealth Home Care, and Phoenix-area Medicare-certified independents all appear in the federal data.

A geographic note: most Phoenix-listed agencies serve the broader Phoenix metro (Maricopa County) including Tempe, Scottsdale, Mesa, Glendale, and the West Valley suburbs. Confirm in writing which municipalities an agency covers and the rates for caregivers traveling between locations. The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers the rest. This page is informational; agency selection and verification rest with the family.""",

    "minneapolis": """The Twin Cities home-care market reflects the broader Minnesota approach to long-term services and supports — a state that has historically invested heavily in home and community-based care as an alternative to institutional placement. Minnesota's Elderly Waiver and Alternative Care programs are among the more comprehensive state-funded home-care benefits in the country and shape how the local market operates. The 48 agencies serving Minneapolis on this page reflect that scale: a mix of large hospital-affiliated home-health networks (Allina Home Health, Fairview Home Care, M Health Fairview, Park Nicollet, HealthPartners), nonprofit visiting nurse services, national-franchise personal-care brands (Comfort Keepers, Home Instead, Visiting Angels, BrightStar, Right at Home), and independently-owned local agencies. Coverage frequently extends beyond Minneapolis proper into Hennepin and Ramsey counties and the inner-ring suburbs; some agencies serve as far out as Anoka, Dakota, Carver, and Washington counties.

Minnesota licenses home-care providers through the Department of Health, [Home Care Provider Regulation](https://www.health.state.mn.us/). The state's licensing regime is somewhat unusual in that it covers both comprehensive home-care providers (which can deliver any home-care service including hands-on personal care, medication assistance, and skilled nursing) and basic home-care providers (limited to non-medical services like homemaking, companion care, and standby assistance). The license type matters for what the agency is permitted to do — confirm in writing which license type your prospective agency holds and check that it covers the services contracted.

The Metropolitan Area Agency on Aging serves the seven-county Twin Cities metro and provides assessments, provider directories, and care-coordination services for eligible seniors. The Senior LinkAge Line — Minnesota's statewide aging-services helpline — is also a useful first call for families unsure where to start.

For families using Minnesota Health Care Programs (MHCP, Minnesota's Medicaid program), eligibility for in-home services is typically established through a community-based assessment, and care is coordinated through one of the state's integrated managed-care plans (Blue Plus, HealthPartners, Hennepin Health, Medica, UCare, and others). Each plan contracts with a network of home-care providers; an agency on this page that takes Medicaid is typically network-affiliated with one or more.

For Medicare-certified agencies in the Twin Cities metro, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) is the authoritative federal data source — quality star ratings, patient-experience survey results, and any recent surveyor findings. We provide this directory as a starting point. The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) is the first read before any engagement.""",

    "fredericksburg": """Fredericksburg sits in the corridor between the Washington, DC metro and Richmond, and the home-care market on this page reflects that geography. Many of the 47 agencies listed serve clients across Spotsylvania, Stafford, King George, and Caroline counties, and a meaningful subset also reaches into the southern fringe of Northern Virginia (Prince William, Stafford). The corridor includes the Marine Corps Base Quantico footprint to the north and the broader Virginia military-retiree population that radiates out from Fort Belvoir, the Pentagon, and the Hampton Roads naval bases — a substantial veteran subset of the Fredericksburg-area senior population uses VA-funded home care as a primary or supplemental payment source.

Service-area scope matters for families coordinating care across the region, particularly for adult children commuting between Northern Virginia and a parent in or near Fredericksburg. Confirm in writing which county or counties an agency serves and the rates for caregivers traveling between locations. Some agencies bill differently for Stafford-vs.-Spotsylvania-vs.-Caroline service area; some have minimum-shift requirements that effectively rule out short check-in visits in outlying counties; some require minimum case sizes that don't fit episodic post-discharge needs. These details matter on the first call, not the third.

Virginia regulates home-care organizations through the Department of Health, [Office of Licensure and Certification](https://www.vdh.virginia.gov/). The state licenses home-care organizations as a distinct category from home-health agencies; both license types operate in the Fredericksburg metro. The Commonwealth Coordinated Care Plus Medicaid managed-care program is a major payer for eligible seniors and is administered through Medicaid managed-care organizations (Aetna Better Health, Anthem HealthKeepers, Sentara Community Plan, United Healthcare, Virginia Premier).

The Rappahannock Area Agency on Aging serves the Fredericksburg region (Caroline, King George, Spotsylvania, Stafford, and the City of Fredericksburg) and provides care-coordination services and provider directories. They are a useful second source when families are weighing options.

Medicare-certified agencies are tracked on Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool with quality star ratings, patient-experience survey results, and any recent surveyor findings. This directory lists agencies; we don't recommend any one. The [verification guide](/guides/how-to-verify-a-home-care-agency.html) covers what to do before engagement.""",

    "louisville": """Louisville's home-care landscape sits in the Ohio River Valley and overlaps materially with Southern Indiana. Several of the 44 agencies serving Louisville on this page also operate in New Albany, Jeffersonville, and Clarksville on the Indiana side; a handful are headquartered in Indiana but serve Jefferson County, Kentucky as part of their primary geography. For families coordinating care across the bi-state metro, the cross-state license question matters: Kentucky and Indiana license home-care services separately, and an agency operating in both states should hold both licenses for the work it performs in each. Verify the appropriate state's license for the service location, not just the agency's headquarters.

Kentucky's regulatory home for home-care licensing is the Cabinet for Health and Family Services, [Office of Inspector General](https://chfs.ky.gov/). Indiana licenses through the Department of Health ([in.gov/health](https://www.in.gov/health/)). Both states publish license-lookup tools and accept formal complaints against licensed providers.

Kentucky's Medicaid program covers in-home personal care under several pathways, including the Home and Community-Based (HCB) waiver, the Acquired Brain Injury waiver, and the Michelle P. waiver. Eligible Louisville-area seniors typically work through the Kentuckiana Regional Planning and Development Agency (KIPDA) Area Agency on Aging or through a Medicaid managed-care organization (Aetna Better Health of Kentucky, Anthem Medicaid, Humana Healthy Horizons, Passport Health Plan, UnitedHealthcare, WellCare) for care coordination. KIPDA serves Jefferson, Bullitt, Henry, Oldham, Shelby, Spencer, and Trimble counties on the Kentucky side.

Louisville also has a substantial veteran population through the Robley Rex VA Medical Center catchment, and VA Aid and Attendance benefits cover in-home care for qualifying veterans and surviving spouses. Several Louisville-listed agencies focus on VA-funded care.

Medicare-certified agencies operating in either Kentucky or Indiana appear in Medicare's [Care Compare](https://www.medicare.gov/care-compare/) database with quality star ratings and patient-experience scores. Norton Healthcare, Baptist Health, and UofL Health all operate Medicare-certified home health agencies serving the Louisville metro; smaller independent and franchise-affiliated operators also appear.

We list agencies; we don't recommend any one. See the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) for the four checks we'd do before engaging — license, references, caregiver vetting, and Care Compare for the certified subset.""",

    "fort-myers": """Florida regulates home-care services more comprehensively than most states. The Agency for Health Care Administration ([ahca.myflorida.com](https://ahca.myflorida.com/)) licenses home health agencies, nurse registries, and home-care services agencies as separate categories. The license type matters: a home health agency can deliver Medicare-certified skilled care under federal certification; a nurse registry is a referral service that places independent caregivers (with a different liability profile for the family — the nurse-registry caregiver is typically not an agency employee, so worker's-compensation, taxes, and supervision sit with the family); a home-care services agency provides non-medical companion and personal care under contract. Before signing, confirm in writing which license category your prospective agency holds and how it matches the family's needs. The wrong license type for the wrong service creates real legal and practical problems.

For the 44 agencies serving Fort Myers on this page, the regulator-published license-lookup tool on AHCA's site is the first verification. AHCA also publishes survey results and complaint history. The Florida Statewide Medicaid Managed Care Long-Term Care (SMMC LTC) program is administered through Medicaid managed-care organizations, and many Fort Myers-area agencies are network providers for one or more SMMC LTC plans.

Southwest Florida has a high concentration of seasonal residents — the snowbird population that arrives each fall and departs each spring — which produces a particular service-mix pattern in the local home-care market. Several agencies on this page specialize in short-stay coverage for seasonal residents, with arrangements that scale up for winter months and down for summer. Confirm in writing how an agency handles seasonal residents and whether the agency can re-engage caregivers from prior seasons (caregiver continuity matters more for memory care than for companion care, but matters in both).

For Medicare-certified agencies, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) provides additional federal data — overall quality star ratings, patient-experience survey results (HHCAHPS), and any recent surveyor findings. Read sample sizes alongside ratings.

Lee County (Fort Myers, Cape Coral) and the broader Southwest Florida region also have Area Agencies on Aging — Senior Choices of Southwest Florida is the regional AAA for Lee, Charlotte, Hendry, Glades, and Collier counties. The AAA maintains provider directories, conducts in-home assessments for Medicaid eligibility, and provides care-coordination services. They are funded under the federal Older Americans Act with a defined oversight role.

For families with veterans in the household — Southwest Florida has a substantial military-retiree population — VA Aid and Attendance pension benefits cover in-home care for qualifying veterans and surviving spouses. The [verification guide](/guides/how-to-verify-a-home-care-agency.html) covers the rest of the diligence work. This directory is informational, not a ranking.""",

    "columbia": """Columbia families typically come to home-care decisions with one of a few specific problems in mind: keeping a parent in the home through a memory-care decline; supporting recovery after a hospital discharge; bridging family caregivers stretched between Columbia and out-of-state employers; or managing care for a veteran. South Carolina has a substantial veteran population through Fort Jackson, Shaw Air Force Base, and broader military-retiree ties, so VA-funded home care is a common payment path on this page. The 43 agencies on this directory page collectively address each of those scenarios, though no single agency does all of them equally well. Before contacting any of them, write down the actual care need — services, schedule, payment source — and use that as the screen.

South Carolina's regulatory landscape for home care changed in 2024. The South Carolina Department of Public Health ([dph.sc.gov](https://dph.sc.gov/)) was formed when the former South Carolina Department of Health and Environmental Control (SCDHEC) was split into separate environmental and public-health agencies. Public-health regulation, including home-care licensure, now sits with SCDPH. Verify the license is current and recent before engaging — the regulator transition created some database-migration questions in the months immediately after the split, but the system is now stable.

South Carolina Healthy Connections Medicaid covers in-home personal care under the Community Choices waiver and other home and community-based program structures. Eligible Columbia-area seniors typically work through the Central Midlands Council of Governments Area Agency on Aging or through one of the state's Medicaid managed-care plans for care coordination. The Central Midlands AAA serves Richland, Lexington, Newberry, and Fairfield counties.

For Columbia's substantial veteran population, the William Jennings Bryan Dorn VA Medical Center is the local VA facility, and several agencies on this page specialize in VA-billed care under the Aid and Attendance pension benefit, the Homemaker/Home Health Aide program, and the Veteran Directed Care program.

For Medicare-certified agencies, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes quality star ratings and patient-experience survey results. Prisma Health, Lexington Medical Center home services, and several independent and franchise operators handle Medicare-certified work in the Columbia metro.

A geographic note: Columbia-area agencies typically serve the broader Midlands region — Richland, Lexington, Newberry, Kershaw, and parts of Calhoun and Fairfield counties. Confirm in writing the actual service area for your loved one's home address. Use the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) for license, references, caregiver vetting, and Care Compare interpretation. We list agencies; verification before engagement is the family's responsibility.""",

    "mesa": """Mesa's 42 home-care agencies tilt the service mix toward what an East Valley senior population most often asks for: personal care and companion care for aging-in-place, dementia and Alzheimer's care, post-surgery recovery, and a meaningful subset offering live-in coverage as a cost alternative to assisted living. Hospice support is commonly listed, reflecting the East Valley's relatively high concentration of late-life-stage residents who have aged in place since the metro's mid-twentieth-century retirement-community development. Bilingual care (English-Spanish predominantly) is widely available, which matters for the metro's Hispanic senior population. A subset of agencies also offers care for the substantial seasonal-resident community that arrives each fall and departs each spring — short-stay arrangements, caregiver continuity across seasons, and partial-month minimums are practical service distinctions worth asking about.

Service-area scope matters in the East Valley: many Mesa-listed agencies also serve Tempe, Chandler, Gilbert, Apache Junction, and Queen Creek, and a smaller subset reaches into Fountain Hills and the northeast valley. Confirm in writing which Phoenix-metro municipalities an agency covers and the rates for caregivers traveling beyond a primary service area. Some agencies bill differently for Mesa-vs.-outlying-city work; a small minimum-shift requirement that makes sense for a Mesa-core caregiver may be infeasible for a Queen Creek caregiver who needs a longer drive.

Arizona regulates home-care services through the Department of Health Services, Bureau of Medical Facilities Licensing ([azdhs.gov](https://www.azdhs.gov/)). The state's ALTCS (Arizona Long Term Care System) Medicaid program is a major payer for qualifying seniors; ALTCS-eligible care is administered through health plans (Banner University Family Care, Mercy Care, UnitedHealthcare Community Plan, and others) that contract with home-care provider networks. The Area Agency on Aging Region One operates in the Phoenix metro and provides assessment, care-coordination, and provider directories.

Phoenix's substantial veteran population — the Phoenix VA Health Care System, the Carl T. Hayden VA Medical Center — translates into Mesa-area demand for VA-funded home care. VA Aid and Attendance pension benefits and the Veteran Directed Care program cover in-home care for qualifying veterans and surviving spouses.

For Medicare-certified agencies, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool covers the federally-certified subset with quality star ratings and patient-experience survey results. Banner Home Care, HonorHealth Home Care, and several Medicare-certified independents serve the East Valley. Use the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) before engagement. This directory is informational; verification rests with the family.""",

    "akron": """Akron families researching home care typically work through a few practical questions before the first phone call: how many hours of weekly care the family is realistically asking the budget to support, whether the loved one's medical needs require Medicare-certified skilled services or whether non-medical companion and personal care will cover it, and how the family is planning to evaluate caregiver match (some agencies offer a no-cost replacement caregiver if the first match doesn't work out; others charge a re-match fee). The 37 agencies on this page differ across each of those dimensions, and the differences materially affect cost, scheduling flexibility, and the experience after the first month.

Akron's home-care market is shaped by the regional concentration of healthcare employers — Cleveland Clinic Akron General, Summa Health, and several Medicare-certified home-health affiliates of those systems. A subset of the listings on this page is hospital-affiliated and handles post-discharge transitions tightly with the originating hospital. Others are national-franchise personal-care brands (Comfort Keepers, Home Instead, Visiting Angels, BrightStar, Right at Home) or independently-owned local operators. The hospital-affiliated agencies are often the easiest path for Medicare-certified short-term skilled care; the franchise and independent operators typically lead on private-pay personal and companion care.

Ohio regulates home-care services through the Department of Health ([odh.ohio.gov](https://odh.ohio.gov/)). The state's PASSPORT Medicaid waiver — one of the longest-running home and community-based care programs in the country — is administered for the Akron region by the Direction Home Akron Canton Area Agency on Aging, which serves Stark, Summit, Portage, and Wayne counties. Direction Home conducts in-home assessments, maintains a provider directory, and provides care management for enrolled seniors. AAAs are funded under the federal Older Americans Act and have a defined oversight role; their referral list is not a marketing list.

For families with VA-eligible veterans — Akron has a meaningful military-retiree population, and the Wade Park VA Medical Center catchment includes the broader Northeast Ohio region — VA Aid and Attendance benefits cover in-home care for qualifying veterans and surviving spouses.

For Medicare-certified agencies, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes quality star ratings, patient-experience scores, and any recent surveyor findings. The hospital-system home-health agencies and several Medicare-certified independents in the Akron area all appear in the federal data.

A geographic note: Akron-listed agencies typically serve the broader Akron-Canton metro including Cuyahoga Falls, Stow, Tallmadge, Barberton, Norton, and parts of Portage and Stark counties. Confirm service coverage in writing. The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers the four checks we'd recommend running before engagement. Listings are informational; we don't recommend specific agencies.""",

    "worcester": """Central Massachusetts is the regional context for Worcester's 36 home-care agencies. The Worcester metro draws a service area that frequently extends into the broader Worcester County (Auburn, Shrewsbury, Holden, Westborough, Grafton, Millbury, Leicester, Spencer) and parts of Middlesex and Hampden counties. Several Worcester-listed agencies serve clients across this regional footprint, and the practical question for any family is which county or counties their loved one's home falls into and whether the agency covers it without travel surcharges. Worcester is also a regional medical hub — UMass Memorial Health, Saint Vincent Hospital, and the broader UMass Chan Medical School ecosystem produce a strong supply of clinical talent and a corresponding depth of Medicare-certified home health agencies.

Massachusetts regulates home-care services through the Department of Public Health, Bureau of Health Care Safety and Quality ([mass.gov](https://www.mass.gov/)). MassHealth — the state Medicaid program — is one of the country's most comprehensive payers for home and community-based services. Many Worcester-area agencies are MassHealth network providers. The state's Senior Care Options (SCO) and One Care programs serve dual-eligible (Medicare + Medicaid) seniors with integrated care management; these programs typically channel home-care referrals through contracted plans (Senior Whole Health, Tufts Health Plan SCO, Commonwealth Care Alliance, Fallon, NaviCare).

The Massachusetts Executive Office of Elder Affairs operates an Aging Services Access Point (ASAP) network that vets and refers to home-care providers in Worcester County. Elder Services of Worcester Area is the local ASAP and serves Worcester, Shrewsbury, Auburn, and surrounding communities; Tri-Valley Inc. covers parts of southern Worcester County. ASAPs conduct in-home assessments for state-funded home-care eligibility, manage care plans, and maintain provider directories.

For families with VA-eligible veterans — Massachusetts has a meaningful veteran population, and the VA Central Western Massachusetts Healthcare System operates several outpatient facilities in the region — VA Aid and Attendance pension benefits cover in-home care for qualifying veterans and their surviving spouses.

Medicare-certified agencies appear on Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool with quality star ratings, patient-experience survey results, and any recent surveyor findings. UMass Memorial Home Health and Hospice, Saint Vincent Home Care, and several Medicare-certified independents serve the Worcester metro.

The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) is the first read before engagement. We don't recommend specific agencies; the directory is informational, and verification rests with the family.""",

    "southfield": """Southfield sits at the intersection of Oakland County and Wayne County, on the northwestern fringe of the Detroit metro. The 36 agencies on this page reflect that geography. Many serve clients across Oakland (Birmingham, Bloomfield, Royal Oak, Farmington Hills, Troy, West Bloomfield, Novi) and into the Detroit core (Redford, Livonia, parts of Detroit). A handful reach further into Macomb County (Warren, St. Clair Shores, Sterling Heights). As is common in metro markets, agency listings give a Southfield address but the practical service area can be much broader. For families considering home care for a loved one in Pontiac, Westland, Warren, or further out, ask the agency in writing whether they serve the specific home address and at what rates. Several Southfield-listed agencies are headquarters offices for chains that operate across the broader Detroit metro under the same brand.

Michigan regulates home-care services through the Department of Licensing and Regulatory Affairs ([michigan.gov/lara](https://www.michigan.gov/lara)). LARA's Bureau of Community and Health Systems handles home-care agency licensing inquiries and complaints. The MI Choice Medicaid waiver is a meaningful payment path for eligible seniors who would otherwise need nursing-facility-level care and covers personal care, homemaking, respite, and other home and community-based services. The Area Agency on Aging 1-B serves the Detroit-area suburbs (Livingston, Macomb, Monroe, Oakland, St. Clair, and Washtenaw counties) and conducts MI Choice eligibility assessments, maintains provider directories, and provides care-management services. Detroit Area Agency on Aging serves the City of Detroit and the Hamtramck-Highland Park subset of Wayne County. AAAs are funded under the federal Older Americans Act.

For families with VA-eligible veterans — Detroit has a substantial veteran population through the John D. Dingell VA Medical Center catchment — VA Aid and Attendance benefits, the Homemaker/Home Health Aide program, and the Veteran Directed Care program all cover in-home care for qualifying veterans and surviving spouses.

Medicare-certified agencies in the Detroit metro appear on Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool with quality star ratings, patient-experience survey results (HHCAHPS), and any recent surveyor findings. Henry Ford Home Health Care, Beaumont Home Care, McLaren Home Health, and several Medicare-certified independents and franchise operators all serve the metro.

The [verification guide](/guides/how-to-verify-a-home-care-agency.html) covers what to do before engaging — license verification, real client references, caregiver-vetting questions, and Care Compare interpretation for the certified subset. Listings are informational; we don't recommend any one agency.""",

    "dayton": """Ohio's state regulator for home-care services is the Department of Health, with separate licensing tracks for Medicare-certified home health agencies and other home-care service providers. Verify the appropriate license type before engaging any of the 35 agencies serving Dayton on this page; the Department of Health's facility-licensing portal at [odh.ohio.gov](https://odh.ohio.gov/) is the first stop. The portal supports license lookup, complaint filing, and survey-results retrieval for licensed providers.

Beyond licensure, the Ohio PASSPORT Medicaid waiver — one of the longest-running home and community-based services programs in the country — is a major payment path for eligible Dayton-area seniors. The Area Agency on Aging Region 2 (PSA 2), Area Agency on Aging West Central Ohio for some adjacent counties, and the Council on Aging of Southwestern Ohio for parts of the Miami Valley collectively coordinate PASSPORT enrollment and care management for the region. AAAs conduct in-home assessments, maintain provider directories, and offer ongoing care coordination for enrolled seniors. They are funded under the federal Older Americans Act and operate as a defined-role intermediary between families and the home-care market.

Dayton has a substantial veteran population through Wright-Patterson Air Force Base, the Dayton VA Medical Center, and the broader Department of Defense and federal-civilian retiree presence in the metro. VA Aid and Attendance pension benefits and the Veteran Directed Care program both cover in-home care for qualifying veterans and surviving spouses, and several Dayton-listed agencies focus on VA-funded care.

For families coordinating care across the metro, Dayton-area agencies typically serve Montgomery County (Dayton, Kettering, Centerville, Beavercreek, Vandalia, Huber Heights, Trotwood) and reach into Greene, Miami, Warren, and parts of Clark and Preble counties. Confirm in writing the agency's coverage for your loved one's home address.

For Medicare-certified agencies, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes overall quality star ratings, patient-experience survey results, and any recent surveyor findings. Ohio's Premier Health, Kettering Health, and several Medicare-certified independents serve the Dayton metro.

The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers references, caregiver vetting, and Care Compare interpretation. This page lists agencies; we don't rank or recommend any one of them. Verification before engagement is the family's responsibility.""",

    "washington": """The District of Columbia is its own regulatory jurisdiction, though the Washington-area home-care market spans DC proper, Northern Virginia (Arlington, Alexandria, Fairfax, Loudoun, Prince William), and suburban Maryland (Montgomery, Prince George's, Charles, Frederick). Several of the 34 agencies serving Washington listed on this page also operate in Virginia or Maryland; a handful are tri-jurisdictional. The licensure question matters: an agency providing care in a DC home must hold a DC license; an agency providing care in a Maryland home must hold a Maryland license; an agency providing care in a Virginia home must hold a Virginia license. Headquarters location alone is not sufficient. For families coordinating care for a parent who lives in suburban Maryland but is hospitalized in DC for a procedure, the discharging agency may need different credentials than the long-term home-care agency that picks up the case after.

DC regulates home-care agencies through the Department of Health, Health Regulation and Licensing Administration ([dchealth.dc.gov](https://dchealth.dc.gov/)). HRLA's licensing portal supports license lookup and complaint filing. The DC Department of Aging and Community Living (DACL) is the local Area Agency on Aging and administers home and community-based services for eligible DC-resident seniors. DACL conducts assessments, maintains provider directories, and provides care coordination.

DC's Elderly and Persons with Physical Disabilities (EPD) Waiver — administered through DC Medicaid — is the principal Medicaid pathway for in-home care for eligible DC-resident seniors. Care is delivered by EPD-network agencies under the DC Medicaid managed-care framework.

For DC's substantial veteran population — the Washington DC VA Medical Center is one of the larger VA facilities in the country, serving veterans from across the metro and from federal-civilian retirees with VA-eligibility through prior service — VA Aid and Attendance pension benefits and the Veteran Directed Care program both cover in-home care.

For Medicare-certified agencies serving the DC metro, Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool publishes quality star ratings, patient-experience survey results, and any recent surveyor findings. MedStar Health Home Care, INOVA Home Health, and several Medicare-certified independents and franchise operators serve the metro.

We list agencies. The [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) is the first read before engaging any of them — license verification, real client references, caregiver-vetting questions, and Care Compare interpretation are the four checks that apply regardless of jurisdiction.""",

    "las-cruces": """The 34 home-care agencies serving Las Cruces in this directory tend to focus on a particular service mix shaped by the Mesilla Valley's senior population. Personal care, companion care, dementia and Alzheimer's care, and live-in or extended-shift coverage are widely available. Bilingual English-Spanish caregivers are common — for families with a loved one whose first language is Spanish, language match is often the single most important factor in caregiver satisfaction. Several agencies serve clients across Doña Ana County and into the broader Borderplex region (the El Paso metro just south, plus Sunland Park and Anthony at the New Mexico-Texas line); a few specialize in care for clients who travel between Las Cruces and El Paso for medical appointments at Las Palmas Del Sol or Hospitals of Providence.

Service-area considerations matter: some Las Cruces-listed agencies serve only the city core; others reach into Anthony, Sunland Park, Mesilla, La Mesa, Hatch, and as far as Truth or Consequences. Confirm in writing which service area an agency covers and the rates for caregivers traveling outside it. For Borderplex families coordinating care across the New Mexico-Texas state line, separate state licensure is required for each side; an agency operating in El Paso must hold Texas Health and Human Services licensure for that work.

New Mexico regulates home-care services through the Department of Health, Division of Health Improvement ([nmhealth.org](https://www.nmhealth.org/)). The state's Centennial Care Medicaid managed-care program is the principal Medicaid pathway for in-home care for eligible seniors and is administered through contracted health plans (Blue Cross Community Centennial, Presbyterian Centennial Care, Western Sky Community Care, and others). The state's Mi Via self-directed program allows eligible seniors to manage their own care budget and select caregivers — an alternative payment pathway that some Las Cruces-listed agencies support.

The Non-Metro Area Agency on Aging serves Doña Ana County and the broader southern New Mexico region; the New Mexico Aging and Long-Term Services Department administers the state's aging-services network. The AAA conducts assessments, maintains provider directories, and provides care coordination for eligible seniors.

For the substantial veteran population in southern New Mexico — White Sands Missile Range, Holloman Air Force Base, Fort Bliss across the Texas border — VA Aid and Attendance pension benefits cover in-home care for qualifying veterans and surviving spouses.

Medicare-certified agencies appear on Medicare's [Care Compare](https://www.medicare.gov/care-compare/) tool with quality star ratings, patient-experience survey results, and any recent surveyor findings.

This directory is informational; the [how-to-verify guide](/guides/how-to-verify-a-home-care-agency.html) covers what to do before engaging any specific agency.""",
}
